# Site settings
title: Rasmus Rygaard
email: rasmus@rasmusrygaard.com
description: "rasmusrygaard.com, very much a work in progress."
baseurl: ""
url: "http://rasmusrygaard.com.com"
github_username:  rasmusrygaard

# Build settings
markdown: kramdown
permalink: pretty

assets:
  js_compressor: uglifier
