# Site settings
title: Rasmus Rygaard
email: rasmus@rasmusrygaard.com
description: "rasmusrygaard.com, very much a work in progress."
baseurl: ""
url: "http://rasmusrygaard.com.com"
github_username:  rasmusrygaard

# Build settings
markdown: redcarpet
redcarpet: 
  extensions: [fenced_code_blocks, footnotes]
permalink: pretty


assets:
  js_compressor: uglifier
  css_compressor: sass
  gzip: [ text/css, application/javascript, image/jpeg ]

sass:
    sass_dir: _assets/stylesheets
